#!/usr/bin/env python
# coding: utf8

"""
Convert a .cndb (HDF5) trajectory file to an .pdb text format for Nucleome Data Bank.

to run:
python3 cndb2pdb.py -f <filename>.cndb -n <output_filename>
*just do the output filename, it will add .pdb automatically and will be located in the same directory as the input file.
"""

import argparse
import numpy as np
import h5py
import time
from pathlib import Path

# ------------------------- Argument Parser -------------------------
parser = argparse.ArgumentParser(description="Convert CNDB to NDB format")
parser.add_argument("-f", required=True, help="Input .cndb HDF5 file")
parser.add_argument("-n", default="output", help="Base name for output .ndb file")
parser.add_argument("-res", default=50000, type=int, help="Resolution in bp")
parser.add_argument("-chroID", default="C", help="Chromosome chain ID")
parser.add_argument("-sigma", default=0.000, type=float, help="Fluctuation sigma")
parser.add_argument("-scale", default=1.000, type=float, help="Distance scale")
args = parser.parse_args()

start_time = time.time()

# ------------------------ Load .cndb File --------------------------
cndb_file = Path(args.f)
if not cndb_file.exists():
    raise FileNotFoundError(f"Input file not found: {args.f}")

f = h5py.File(cndb_file, "r")
types = list(f["types"].asstr())

try:
    loops = np.array(f["loops"])
    has_loops = True
except KeyError:
    has_loops = False

frames = sorted(k for k in f.keys() if k.isdigit())


#Travis additions
# print('args.f:', args.f)
# print('args.n:', args.n)

pathLoc = args.f.rfind('/')
path = args.f[:pathLoc+1] if pathLoc != -1 else './'
pathN = path + args.n
print('pathN:', pathN)




# ---------------------- Write .ndb Header --------------------------
# with open(args.n + ".ndb", "w") as out:
with open(pathN + ".ndb", "w") as out:
    out.write("HEADER    Converted from CNDB\n")
    out.write("TITLE     Generated by cndb2ndb.py\n")
    out.write("AUTHOR    Auto-generated\n")
    out.write("EXPDTA    Simulated\n")

    # Write SEQCHR entries
    for i, chunk in enumerate([types[x:x+23] for x in range(0, len(types), 23)]):
        out.write(f"SEQCHR {i+1:3d} {args.chroID:2s} {len(types):5d}  {' '.join(chunk):69s}\n")

    # ------------------ Write Each Frame ----------------------
    for frame_id in frames:
        data = np.array(f[frame_id])
        out.write(f"MODEL     {int(frame_id):4d}\n")

        for i, (x, y, z) in enumerate(data):
            subtype = types[i] if i < len(types) else 'UN'
            start = i * args.res + 1
            end = (i + 1) * args.res
            out.write(f"CHROM  {i+1:8d} {subtype:2s}       {args.chroID:4s} {i+1:8d} {x:8.3f} {y:8.3f} {z:8.3f} {start:10d} {end:10d} {args.sigma:8.3f}\n")

        out.write(f"TER   {len(data)+1:8d} {subtype:2s}        {args.chroID}\n")
        out.write("ENDMDL\n")

    # ------------------ Write Loops --------------------------
    if has_loops:
        for i, j in loops:
            out.write(f"LOOPS  {i:8d} {j:8d}\n")

    out.write("END\n")

print(f"Converted {len(frames)} frames from {args.f} to {args.n}.ndb")
print("Elapsed time: %.2f seconds" % (time.time() - start_time))


#run exit() if trying to do cndb2ndb
# exit()

##to make it convert straight from cndb to pdb
import subprocess
subprocess.run(f"python3 ~/back_scripts/ndb2pdb.py -f {pathN}.ndb -n {pathN}", shell=True, check=True)
#delete the ndb file after conversion
# subprocess.run(f"rm -r {pathN}.ndb", shell=True, check=True)
